- hosts: all
  vars: []
  tasks:
    - name: pull ELK container
      docker_image:
        name: sebp/elk
    - name: run ELK container
      docker_container:
        image: sebp/elk
        name: elk
        state: started
        ports:
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"
